//! The 64 lump slots, and the expected element stride of each.

use crate::raw;

/// Lump directory index. Values match the `LUMP_*` enum in `bspfile.h`.
#[repr(usize)]
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum LumpId {
    Entities = 0,
    Planes = 1,
    TexData = 2,
    Vertexes = 3,
    Visibility = 4,
    Nodes = 5,
    TexInfo = 6,
    Faces = 7,
    Lighting = 8,
    Occlusion = 9,
    Leafs = 10,
    FaceIds = 11,
    Edges = 12,
    SurfEdges = 13,
    Models = 14,
    WorldLights = 15,
    LeafFaces = 16,
    LeafBrushes = 17,
    Brushes = 18,
    BrushSides = 19,
    Areas = 20,
    AreaPortals = 21,
    Unused0 = 22,
    Unused1 = 23,
    Unused2 = 24,
    Unused3 = 25,
    DispInfo = 26,
    OriginalFaces = 27,
    PhysDisp = 28,
    PhysCollide = 29,
    VertNormals = 30,
    VertNormalIndices = 31,
    DispLightmapAlphas = 32,
    DispVerts = 33,
    DispLightmapSamplePositions = 34,
    GameLump = 35,
    LeafWaterData = 36,
    Primitives = 37,
    PrimVerts = 38,
    PrimIndices = 39,
    PakFile = 40,
    ClipPortalVerts = 41,
    Cubemaps = 42,
    TexDataStringData = 43,
    TexDataStringTable = 44,
    Overlays = 45,
    LeafMinDistToWater = 46,
    FaceMacroTextureInfo = 47,
    DispTris = 48,
    PhysCollideSurface = 49,
    WaterOverlays = 50,
    LeafAmbientIndexHdr = 51,
    LeafAmbientIndex = 52,
    LightingHdr = 53,
    WorldLightsHdr = 54,
    LeafAmbientLightingHdr = 55,
    LeafAmbientLighting = 56,
    XZipPakFile = 57,
    FacesHdr = 58,
    MapFlags = 59,
    OverlayFades = 60,
    OverlaySystemLevels = 61,
    PhysLevel = 62,
    DispMultiblend = 63,
}

impl LumpId {
    /// Every slot, in directory order.
    pub const ALL: [LumpId; raw::HEADER_LUMPS] = {
        // Transmuting an index would need unsafe; spell the table out instead
        // so the compiler checks it against the enum.
        use LumpId::*;
        [
            Entities,
            Planes,
            TexData,
            Vertexes,
            Visibility,
            Nodes,
            TexInfo,
            Faces,
            Lighting,
            Occlusion,
            Leafs,
            FaceIds,
            Edges,
            SurfEdges,
            Models,
            WorldLights,
            LeafFaces,
            LeafBrushes,
            Brushes,
            BrushSides,
            Areas,
            AreaPortals,
            Unused0,
            Unused1,
            Unused2,
            Unused3,
            DispInfo,
            OriginalFaces,
            PhysDisp,
            PhysCollide,
            VertNormals,
            VertNormalIndices,
            DispLightmapAlphas,
            DispVerts,
            DispLightmapSamplePositions,
            GameLump,
            LeafWaterData,
            Primitives,
            PrimVerts,
            PrimIndices,
            PakFile,
            ClipPortalVerts,
            Cubemaps,
            TexDataStringData,
            TexDataStringTable,
            Overlays,
            LeafMinDistToWater,
            FaceMacroTextureInfo,
            DispTris,
            PhysCollideSurface,
            WaterOverlays,
            LeafAmbientIndexHdr,
            LeafAmbientIndex,
            LightingHdr,
            WorldLightsHdr,
            LeafAmbientLightingHdr,
            LeafAmbientLighting,
            XZipPakFile,
            FacesHdr,
            MapFlags,
            OverlayFades,
            OverlaySystemLevels,
            PhysLevel,
            DispMultiblend,
        ]
    };

    #[inline]
    pub fn index(self) -> usize {
        self as usize
    }

    /// The `LUMP_*` name, for diagnostics.
    pub fn name(self) -> &'static str {
        use LumpId::*;
        match self {
            Entities => "ENTITIES",
            Planes => "PLANES",
            TexData => "TEXDATA",
            Vertexes => "VERTEXES",
            Visibility => "VISIBILITY",
            Nodes => "NODES",
            TexInfo => "TEXINFO",
            Faces => "FACES",
            Lighting => "LIGHTING",
            Occlusion => "OCCLUSION",
            Leafs => "LEAFS",
            FaceIds => "FACEIDS",
            Edges => "EDGES",
            SurfEdges => "SURFEDGES",
            Models => "MODELS",
            WorldLights => "WORLDLIGHTS",
            LeafFaces => "LEAFFACES",
            LeafBrushes => "LEAFBRUSHES",
            Brushes => "BRUSHES",
            BrushSides => "BRUSHSIDES",
            Areas => "AREAS",
            AreaPortals => "AREAPORTALS",
            Unused0 => "UNUSED0",
            Unused1 => "UNUSED1",
            Unused2 => "UNUSED2",
            Unused3 => "UNUSED3",
            DispInfo => "DISPINFO",
            OriginalFaces => "ORIGINALFACES",
            PhysDisp => "PHYSDISP",
            PhysCollide => "PHYSCOLLIDE",
            VertNormals => "VERTNORMALS",
            VertNormalIndices => "VERTNORMALINDICES",
            DispLightmapAlphas => "DISP_LIGHTMAP_ALPHAS",
            DispVerts => "DISP_VERTS",
            DispLightmapSamplePositions => "DISP_LIGHTMAP_SAMPLE_POSITIONS",
            GameLump => "GAME_LUMP",
            LeafWaterData => "LEAFWATERDATA",
            Primitives => "PRIMITIVES",
            PrimVerts => "PRIMVERTS",
            PrimIndices => "PRIMINDICES",
            PakFile => "PAKFILE",
            ClipPortalVerts => "CLIPPORTALVERTS",
            Cubemaps => "CUBEMAPS",
            TexDataStringData => "TEXDATA_STRING_DATA",
            TexDataStringTable => "TEXDATA_STRING_TABLE",
            Overlays => "OVERLAYS",
            LeafMinDistToWater => "LEAFMINDISTTOWATER",
            FaceMacroTextureInfo => "FACE_MACRO_TEXTURE_INFO",
            DispTris => "DISP_TRIS",
            PhysCollideSurface => "PHYSCOLLIDESURFACE",
            WaterOverlays => "WATEROVERLAYS",
            LeafAmbientIndexHdr => "LEAF_AMBIENT_INDEX_HDR",
            LeafAmbientIndex => "LEAF_AMBIENT_INDEX",
            LightingHdr => "LIGHTING_HDR",
            WorldLightsHdr => "WORLDLIGHTS_HDR",
            LeafAmbientLightingHdr => "LEAF_AMBIENT_LIGHTING_HDR",
            LeafAmbientLighting => "LEAF_AMBIENT_LIGHTING",
            XZipPakFile => "XZIPPAKFILE",
            FacesHdr => "FACES_HDR",
            MapFlags => "MAP_FLAGS",
            OverlayFades => "OVERLAY_FADES",
            OverlaySystemLevels => "OVERLAY_SYSTEM_LEVELS",
            PhysLevel => "PHYSLEVEL",
            DispMultiblend => "DISP_MULTIBLEND",
        }
    }

    /// Element stride for the fixed-stride lumps, given the lump's own
    /// version field. `None` for variable-length or opaque lumps (entity
    /// text, visibility bitsets, the pakfile zip, physics blobs).
    ///
    /// The all-maps sweep in `examples/lumpdump.rs` asserts that each such
    /// lump's inflated length is an exact multiple of this — which is what
    /// catches a struct transcribed with the wrong padding.
    pub fn stride(self, version: i32) -> Option<usize> {
        use LumpId::*;
        use core::mem::size_of as sz;
        Some(match self {
            Planes => sz::<raw::DPlane>(),
            TexData => sz::<raw::DTexData>(),
            Vertexes => sz::<raw::DVertex>(),
            Nodes => sz::<raw::DNode>(),
            TexInfo => sz::<raw::TexInfo>(),
            Faces | FacesHdr | OriginalFaces => sz::<raw::DFace>(),
            Lighting | LightingHdr => sz::<raw::ColorRgbExp32>(),
            // The only version-dependent layout in the file.
            Leafs => match version {
                0 => sz::<raw::DLeafV0>(),
                _ => sz::<raw::DLeaf>(),
            },
            Edges => sz::<raw::DEdge>(),
            SurfEdges => sz::<i32>(),
            Models => sz::<raw::DModel>(),
            LeafFaces | LeafBrushes => sz::<u16>(),
            Brushes => sz::<raw::DBrush>(),
            BrushSides => sz::<raw::DBrushSide>(),
            DispInfo => sz::<raw::DDispInfo>(),
            VertNormals => sz::<raw::Vec3>(),
            VertNormalIndices => sz::<u16>(),
            DispVerts => sz::<raw::DispVert>(),
            DispTris => sz::<raw::DispTri>(),
            Cubemaps => sz::<raw::DCubemapSample>(),
            TexDataStringTable => sz::<i32>(),
            FaceIds => sz::<u16>(),
            LeafMinDistToWater => sz::<u16>(),
            _ => return None,
        })
    }
}
