[package]
name = "write-lightmaps"
publish = false
version = "0.14.1"
description = "Rust crate for parsing and operating with Quake 1, 2, and GoldSrc BSP files"
edition = "2024"
authors = ["Noxmore"]
repository = "https://github.com/Noxmore/qbsp"
license = "MIT OR Apache-2.0"

[dependencies]
qbsp = { path = "../.." }
image = { version = "*", default-features = false, features = ["png"] }